# This file wont do us much good in this location, make sure you change the path as directed to continue!

name: docker-cd

on:
  push:
    branches: master # Revert to only watch the Dockerfile after fixed
#     paths:
#       - "**Dockerfile**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: npm install and build webpack
        run: |
          npm install
          npm run build
      - name: upload webpack artifact
        uses: actions/upload-artifact@master
        with:
          name: webpack artifacts
          path: public/
  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        os: [ubuntu-lastest] #, windows-2016]
        node-version: [14.x] # [12.x, 14.x]

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: download webpack artifacts
        uses: actions/download-artifact@master
        with:
          name: webpack artifacts
          path: public
      - name: npm install, and test
        run: |
          npm install
          npm test
        env:
          CI: true
          
  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    needs: test
    name: Docker Build, Tag, Push

    steps:
    - name: Checkout
      uses: actions/checkout@v2

#     - name: Set up QEMU
#       uses: docker/setup-qemu-action@v1

    - name: set up docker buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: image=moby/buildkit:master

    - name: get current date 
      id: date 
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')" 

    - name: download built artifact
      uses: actions/download-artifact@master
      with:
        name: webpack artifacts
        path: public

    - name: login to github container registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: build and publish container image
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./${{ github.workflow }}/
        file: ./${{ github.workflow }}/Dockerfile
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ github.workflow }}:latest
          ghcr.io/${{ github.repository_owner }}/${{ github.workflow }}:${{ steps.date.outputs.date }}
    - name: image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
        
